trigger: none

resources:
  repositories:
  - repository: moswald/azure-pipelines-spfx-templates
    type: github
    name: moswald/azure-pipelines-spfx-templates
    endpoint: VSTS Testing

stages:
- stage: Build
  dependsOn: []
  jobs:
    - template: jobs/build.yml@azure-pipelines-spfx-templates
      parameters:
        working_directory: sample
