trigger: none

resources:
  repositories:
  - repository: azure_pipelines_spfx_templates
    type: github
    name: moswald/azure-pipelines-spfx-templates
    endpoint: moswald-github

stages:
- stage: Build
  dependsOn: []
  jobs:
    - template: jobs/build.yml@azure-pipelines-spfx-templates
      parameters:
        working_directory: sample
