parameters:
  # unique name of the job
  job_name: build_package
  # friendly name of the job
  display_name: SPFx production build & packaging
  # agent pool details (default: MSFT hosted Ubuntu)
  pool: 
    vmImage: ubuntu-latest
  # relative path to the project root if not in root of repo
  working_directory: ''
  # package manager
  package_manager: 'npm'

jobs:
- job: ${{ parameters.job_name }}
  displayName: ${{ parameters.display_name }}
  pool: ${{ parameters.pool }}
  steps:
  ##########################################
  ## install dependencies using specified 
  ##    package manager
  ##########################################
  - script: npm install
    displayName: Install dependencies (NPM)
    workingDirectory: ${{ parameters.working_directory }}
    condition: eq('${{ parameters.package_manager }}', 'npm')
  ##########################################
  ## execute: gulp build
  ##########################################
  - task: Gulp@0
    displayName: SPFx build (v0)
    inputs:
      gulpFile: $(Build.Repository.LocalPath)/${{ parameters.working_directory }}/gulpfile.js
      targets: build

  - task: Gulp@1
    displayName: SPFx build (v1)
    inputs:
      gulpFile: $(Build.Repository.LocalPath)/${{ parameters.working_directory }}/gulpfile.js
      workingDirectory: ${{ parameters.working_directory }}
      targets: build
